### PR TITLE
Configuring OpenTracing for SearchApi

### PR DESCRIPTION
**Pull request by alexjoybc**
This pr includes the following proposed changes:
* Add `openTracing` & `Jaegger` to `SearchApi.Web`
* Configure `docker-compose` with `Jaegger` services

### CODE REVIEW

**Comment by alexjoybc** [comment]
@pdittaro, I can encapsulate the configuration in try-catch and catch `no service name` exception, it will not register the tracer, therefore no trace will be shipped

**Comment by pdittaro** [comment]
An issue with the current implementation is that if we use the sidecar deployment for jaeger and the sidecar container doesn't spin up before the SearchAPI then the SearchAPI will not try and reinitialize its connection.

**Comment by alexjoybc** [comment]
Can't you wait for the jaeger agent to be up before executing `dotnet run` on the main container. I don't see a way to control that in the code yet.

**Comment by pdittaro** [comment]
True, but I think its valid that if you're providing an environment variable for a Jaeger service that if it can't connect to the service it should either fail or retry. 

Retry would be more difficult, but putting a conditional on the environment variable would allow us to imitate that behavior using container restarts.

**Comment by pdittaro** [comment]
In the meantime I'll look into how we can wait for a container to pass its readiness check before starting the SearchAPI.

**Pull request merged**
